#!/bin/bash

################################################################################
###                                                                          ###
###   AS215956.net - Pathvector Updater                                      ###
##########################################                                   ###
###                                                                          ###
###   File      : Run all updates & pathvector & reload configs              ###
###   Version   : 2024.12-001                                                ###
###   Copyright : 2024 (and beyond) - Dennis de Houx, AS215956, All In One   ###
###   Author    : Dennis de Houx <dennis@dehoux.be>                          ###
###   License   : MIT                                                        ###
###                                                                          ###
################################################################################

APP_DIR="/opt/as215956/pathvector"


check_progs() {
    if [[ ! -f "/usr/bin/bgpq4" ]]; then
        echo "Error: bgpq4 could not be found on this system"
        exit 1
    fi
    
    if [[ ! -f "/usr/bin/pathvector" ]]; then
        echo "Error: pathvector could not be found on this system"
        exit 1
    fi
}

help() {
    echo "################################################################################"
    echo "###                                                                          ###"
    echo "###   AS215956.net - Pathvector Updater                                      ###"
    echo "##########################################                                   ###"
    echo "###                                                                          ###"
    echo "###   File      : Run all updates & pathvector & reload configs              ###"
    echo "###   Version   : 2024.12-001                                                ###"
    echo "###   Copyright : 2024 (and beyond) - Dennis de Houx, AS215956, All In One   ###"
    echo "###   Author    : Dennis de Houx <dennis@dehoux.be>                          ###"
    echo "###   License   : MIT                                                        ###"
    echo "###                                                                          ###"
    echo "################################################################################"
    echo ""
    echo "   Syntax ${0} [-l|--log|-h|--help|-v|--version]"
    echo ""
    echo "   Options:"
    echo "     -l|--log     Do not show output and log to file"
    echo "     -v|--version Show version info"
    echo "     -h|--help    Show this help message"
    echo ""
}

version() {
    echo "Version: 2024.12-001"
}

created_by_header() {
    echo "################################################################################"
    echo "###                                                                          ###"
    echo "###   AS215956.net - Pathvector Updater                                      ###"
    echo "##########################################                                   ###"
    echo "###                                                                          ###"
    echo "###   File      : Automatic created by update script                         ###"
    echo "###   Version   : 2024.12-001                                                ###"
    echo "###   Created   : ${CURRENT_DATE}                                                 ###"
    echo "###   Copyright : 2024 (and beyond) - Dennis de Houx, AS215956, All In One   ###"
    echo "###   Author    : Dennis de Houx <dennis@dehoux.be>                          ###"
    echo "###   License   : MIT                                                        ###"
    echo "###                                                                          ###"
    echo "################################################################################"
    echo " "
    echo " "
    echo "# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "# !!!         THIS FILE IS AUTOGENERATED BY AS215956 UPDATE SCRIPTS         !!!"
    echo "# !!!  DO NOT EDIT THIS FILE, CHANGES WILL BE OVERRIDEN ON NEXT GENERATION  !!!"
    echo "# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo " "
    echo " "
    echo " "
}

load_settings() {
    BIRD2_DIR="/etc/bird"
    DEFINITIONS_DIR="${BIRD2_DIR}/definitions"
    CURRENT_DATE=$(date +%d/%m/%Y)
    HEADER=$(created_by_header)
    if [[ ! -f "${APP_DIR}/general.conf" ]]; then
        echo "Error: general definitions file could not be found on this system"
        echo "       ${APP_DIR}/general.conf"
        exit 1
    fi
    . ${APP_DIR}/general.conf
}

check_bird_dirs() {
    echo -n " *** Checking bird directories:"
    if [[ ! -d "${DEFINITIONS_DIR}" ]]; then
        CMD=$(mkdir -p ${DEFINITIONS_DIR})
    fi
    echo " [DONE]"
}

create_general() {
    FILE="${DEFINITIONS_DIR}/general.conf"
    echo -n " *** Create general.conf:"
    echo "${HEADER}" > ${FILE}
    echo "define ROUTER_REGION_CODE = \"${ROUTER_REGION_CODE}\";" >> ${FILE}
    echo "define ROUTER_COUNTRY_CODE = \"${ROUTER_COUNTRY_CODE}\";" >> ${FILE}
    echo "define ROUTER_LOCATION_ID = \"${ROUTER_LOCATION_ID}\";" >> ${FILE}
    echo "define ROUTER_ROUTER_ID = \"${ROUTER_ID}\";" >> ${FILE}
    echo " [DONE]"
}

create_as_set() {
    TEMP_FILE="temp_update.sh"
    VARIABLE=${2}
    ASSET=${3}
    FILE="${DEFINITIONS_DIR}/${VARIABLE}.conf"
    echo -n " *** Loading AS-Set: ${ASSET}"
    CMD="/usr/bin/bgpq4 -tb -l 'define ${VARIABLE}' ${ASSET}"
    echo "#!/bin/bash" > ${TEMP_FILE}
    echo "${CMD}" >> ${TEMP_FILE}
    RES=$(sh ${TEMP_FILE})
    echo "${HEADER}" > ${FILE}
    echo "# ${CMD}" >> ${FILE}
    echo "${RES}" >> ${FILE}
    CMD="rm -f ${TEMP_FILE}"
    echo " [DONE]"
}

create_ospf_range() {
    FILE="${DEFINITIONS_DIR}/MY_OSPF_RANGE.conf"
    ASN=$(echo "${AS_SET_ALL}" | tr ":" " " | awk {'print $1'})
    echo -n " *** Loading AS-Set: OSPF RANGE"
    CMD="/usr/bin/bgpq4 -Ab6 -r 52 -R 128 -l 'define MY_OSPF_RANGE' ${ASN}"
    echo "#!/bin/bash" > temp_update.sh
    echo "${CMD}" >> temp_update.sh
    RES=$(sh temp_update.sh)
    echo "${HEADER}" > ${FILE}
    echo "# ${CMD}" >> ${FILE}
    echo "${RES}" >> ${FILE}
    CMD=$(rm -f temp_update.sh)
    echo " [DONE]"
}


create_as_set_all() {
    if [[ ! -z "${AS_SET_ALL}" ]]; then
        create_as_set "MY_AS_SET_ALL" "${AS_SET_ALL}"
    fi
}

create_as_set_downstream() {
    if [[ ! -z "${AS_SET_DOWNSTREAM}" ]]; then
        create_as_set "MY_AS_SET_DOWNSTREAM" "${AS_SET_DOWNSTREAM}"
    fi
}

create_as_set_upstream() {
    if [[ ! -z "${AS_SET_UPSTREAM}" ]]; then
        create_as_set "MY_AS_SET_UPSTREAM" "${AS_SET_UPSTREAM}"
    fi
}

run_pv() {
    CMD=$(/usr/bin/pathvector -t -v g)
}

main() {
    check_progs
    load_settings
    check_bird_dirs
    create_general
    create_as_set_all
    create_as_set_downstream
    create_as_set_upstream
    create_ospf_range
    run_pv
}


# Options
while getopts "h-:H-:v-:V-:l-:L-:" option; do
    case ${option} in
        h|H)
            help
            exit
        ;;
        v|V)
            version
            exit
        ;;
        l|L)
            main >> /var/log/update_pathvector.log;
            exit
        ;;
        -) case $OPTARG in
                help|Help)
                    help
                    exit
                ;;
                version|Version)
                    version
                    exit
                ;;
                log|Log)
                    main >> /var/log/update_pathvector.log;
                    exit
                ;;
        esac;;
    esac
done

main